using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace TypescriptGen
{
    public class CodeGenerator
    {
        private int _indent;

        private readonly StringBuilder _builder = new();

        public void Indent()
        {
            _indent++;
        }

        public void DisableEsLint()
        {
            _builder.Append(@"/* eslint-disable */
");
        }

        public void Signature()
        {
            _builder.Append(@"/**
 * This file was generated by TypeScriptGen v0.0.3
 * Any changes to this file will be lost if regenerated 
 */
");
        }

        public void Outdent()
        {
            _indent--;
        }

        public void WriteLines(IEnumerable<string> lines, string separator)
        {
            _builder.Append(string.Join("," + Environment.NewLine, lines.Select(l => new string(' ', _indent * 4) + l)));
            _builder.AppendLine();
        }
        
        public void WriteLine(string code)
        {
            _builder.AppendLine(new string(' ', _indent * 4) + code);
        }

        public void StartEnd(string code, Action<CodeGenerator> gen)
        {
            WriteLine(code + " {");
            Indent();
            gen(this);
            Outdent();
            WriteLine("}");
        }

        public void Flush(string filename)
        {
            File.WriteAllText(filename, _builder.ToString());
        }
    }
}