using System.Reflection;
using Microsoft.CodeAnalysis;

namespace typescriptgen
{
    [Generator]
    public class TypescriptSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            
            // Find the main method
            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);
            if (mainMethod is null)
            {
                return;
            }
//
//             // Build up the source code
//             var source = $@"// <auto-generated/>
// using System;
//
// namespace {mainMethod.ContainingNamespace.ToDisplayString()}
// {{
//     public static partial class {mainMethod.ContainingType.Name}
//     {{
//         static partial void HelloFrom(string name) {{
//             Console.WriteLine($""This file was generated on {DateTime.Now}"");
//             Console.WriteLine($""The source Generator says: Hi from '{{name}}'"");
//         }}
//     }}
// }}
// ";
//             var typeName = mainMethod.ContainingType.Name;
//
//             // Add the source code to the compilation
//             context.AddSource($"{typeName}.g.cs", source);
//             
            // Assembly.GetExecutingAssembly().Location
            File.WriteAllText("generated.ts", $"// generated from cs source generator {mainMethod.ContainingType.Name}  {DateTime.Now}...");
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}