using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace typescriptgen
{

    [Generator]
    public class EnumGenerator : IIncrementalGenerator
    {
        
        static bool IsSyntaxTargetForGeneration(SyntaxNode node)
            => node is EnumDeclarationSyntax m && m.AttributeLists.Count > 0;
        
        static EnumDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            // we know the node is a EnumDeclarationSyntax thanks to IsSyntaxTargetForGeneration
            var enumDeclarationSyntax = (EnumDeclarationSyntax)context.Node;

            // loop through all the attributes on the method
            foreach (AttributeListSyntax attributeListSyntax in enumDeclarationSyntax.AttributeLists)
            {
                foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                    {
                        // weird, we couldn't get the symbol, ignore it
                        continue;
                    }

                    INamedTypeSymbol attributeContainingTypeSymbol = attributeSymbol.ContainingType;
                    string fullName = attributeContainingTypeSymbol.ToDisplayString();

                    // Is the attribute the [EnumExtensions] attribute?
                    if (fullName == "NetEscapades.EnumGenerators.EnumExtensionsAttribute")
                    {
                        // return the enum
                        return enumDeclarationSyntax;
                    }
                }
            }

            // we didn't find the attribute we were looking for
            return null;
        }   
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, token) => IsSyntaxTargetForGeneration(node),
                transform: static (context, token) => GetSemanticTargetForGeneration(context)
            );
        }
    }

    [Generator]
    public class TypescriptSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            var sb = new StringBuilder();
            
            
            context.

            foreach (var tree in context.Compilation.SyntaxTrees)
            {
                // sb.AppendLine("Syntax tree");
                // sb.AppendLine(tree.FilePath);
                //
                foreach (var node in tree.GetRoot().DescendantNodes())
                {
                    if (node is ClassDeclarationSyntax)
                    {
                        // nide.
                        sb.AppendLine("We have a class declaration!");
                        sb.Append(node.GetText());
                        // node.IsKind(SyntaxKind.ClassDeclaration);
                        // sb.AppendLine("Descendant node");
                    }

                    // sb.AppendLine(node.GetText().ToString());
                    // sb.Append(tree.GetText());
                }
            }
            
            // context.Compilation.SyntaxTrees.Select(t => t.FilePath)
            //     
            //     Where(c => c.GetRoot().DescendantNodes().type OfType<ControllerBase>()>())
            //
            
            
            // Find the main method
            // var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);
            // if (mainMethod is null)
            // {
            //     return;
            // }
//
//             // Build up the source code
//             var source = $@"// <auto-generated/>
// using System;
//
// namespace {mainMethod.ContainingNamespace.ToDisplayString()}
// {{
//     public static partial class {mainMethod.ContainingType.Name}
//     {{
//         static partial void HelloFrom(string name) {{
//             Console.WriteLine($""This file was generated on {DateTime.Now}"");
//             Console.WriteLine($""The source Generator says: Hi from '{{name}}'"");
//         }}
//     }}
// }}
// ";
//             var typeName = mainMethod.ContainingType.Name;
//
//             // Add the source code to the compilation
//             context.AddSource($"{typeName}.g.cs", source);
//             
            // Assembly.GetExecutingAssembly().Location
            File.WriteAllText("generated.ts", sb.ToString());
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}