using Itecho.TsGen.TsTypes;
using Microsoft.AspNetCore.Mvc.TagHelpers;

namespace Itecho.TsGen;

// dotnet pack
// dotnet tool install --global --add-source ./nupkg inspector  

public static class Program
{
    static void Main(string[] args)
    {
        if (args.Length < 2)
        {
            Console.WriteLine($"typescript generator v{VersionInfo.VersionString}");
            Console.WriteLine("-------------");
            Console.WriteLine("\nUsage:");
            Console.WriteLine("args[0] = assembly path to inspect");
            Console.WriteLine("args[1] = output path for TS models");
            Console.WriteLine("-ignore controllerName1 controllerName2 = ignore controller that matches these names;");
            Console.WriteLine(
                "-explicitReturns = only generate methods that explicit returns a value. Discard generic ActionResult returns.");
            Console.WriteLine("-enum [string|number] = Generate enum value as string or number ");
        }

        var list = ProcessArguments.Process(args.Skip(2));
        foreach (var arg in list)
        {
            switch (arg.Name)
            {
                case "ignore":
                    TsGenArguments.Ignore = arg.Value.Select(f => f.ToLower()).ToList();
                    break;
                case "explicitReturns":
                    TsGenArguments.ExplicitReturns = true;
                    break;
                case "enum":
                    TsGenArguments.EnumValueType = arg.Value.Contains("string") ? TsEnum.TsEnumValueType.String : TsEnum.TsEnumValueType.Number;
                    break;
            }
        }

        var assemblyPath = Path.GetFullPath(args[0]);
        var outputPath = Path.GetFullPath(args[1]);
        Console.WriteLine("Inspecting assembly: " + assemblyPath);
        Console.WriteLine("Output path: " + outputPath);

        
        // make sure directories exists
        Directory.CreateDirectory(outputPath);
        EmptyFolder(Path.Combine(outputPath, TsGenArguments.ControllerFolder));
        EmptyFolder(Path.Combine(outputPath, TsGenArguments.InterfacesFolder));
        
        
        // Loading assembly dependencies from a complete output path
        // using a custom AssemblyLoadContext and AssemblyDependencyResolver
        var loadContext = new DependencyLoadContext(assemblyPath);
        var assembly = loadContext.LoadFromAssemblyPath(assemblyPath);

        var controllers = ControllerInspector.Inspect(assembly);

        var interfaces = TsConverter.Cache.Values
            .OfType<TsInterface>();
        // generate interfaces per fil
        foreach (var @interface in interfaces)
        {
            TsGenerator.GenerateInterface(@interface, outputPath);
        }

        var enums = TsConverter.Cache.Values
            .OfType<TsEnum>();
        
        foreach (var @enum in enums)
        {
            TsGenerator.GenerateEnum(@enum, outputPath);
        }

        foreach (var controller in controllers)
        {
            TsGenerator.GenerateController(controller, outputPath);
        }

        // generate the general http handler
        RequestOptions.Generate().WriteToFile(Path.Combine(outputPath, "requestOptions"));
        // and the http concrete handler for the user to change
        var requestPath = Path.Combine(outputPath, "request.ts");
        if (!File.Exists(requestPath))
        {
            HttpMakeRequestFile.Generate().WriteToFile(requestPath);
        }

        File.WriteAllLines(Path.Combine(outputPath, ".version"), new[]
        {
            $"This folder was generated by Itecho.TSGen v{VersionInfo.VersionString}",
            "Arguments used:",
            "dotnet itecho.tsgen " + string.Join(" ", args)
        });
    }

    private static void EmptyFolder(string folder)
    {
        if (Directory.Exists(folder))
        {
            Directory.Delete(folder, true);
        }

        Directory.CreateDirectory(folder);
    }
}