using System.Reflection;
using Itecho.TsGen.TSExpressions;
using Itecho.TsGen.TsTypes;

namespace Itecho.TsGen;

// dotnet pack
// dotnet tool install --global --add-source ./nupkg inspector  

public static class Program
{
    static void Main(string[] args)
    {
        if (args.Length == 0)
        {
            var versionString = Assembly.GetEntryAssembly()?
                .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?
                .InformationalVersion;

            Console.WriteLine($"typescript generator v{versionString}");
            Console.WriteLine("-------------");
            Console.WriteLine("\nUsage:");
            return;
        }

        var assemblyPath = args[0];
        Console.WriteLine("Inspecting assembly: " + assemblyPath);

        // Loading assembly dependencies from a complete output path
        // using a custom AssemblyLoadContext and AssemblyDependencyResolver
        var loadContext = new DependencyLoadContext(assemblyPath);
        var assembly = loadContext.LoadFromAssemblyPath(assemblyPath);


        var controllers = ControllerInspector.Inspect(assembly);

        var interfaces = TsConverter.Cache.Values
            .OfType<TsInterface>()
            .ToList();

        // generate interfaces per file
        foreach (var @interface in interfaces)
        {
            var tsFile = new TsFile();
            tsFile.AddBody(TsExp.MultilineComment(
                "This file was generated by TypeScriptGen v0.0.2",
                "Any changes to this file will be lost if regenerated"));

            tsFile.WriteToFile(Path.Combine("/Users/willem/projects/itest-leaf/Web/ClientApp/src/controllers",
                @interface.Name));

            // var tsCodeGenerator = new TsCodeGenerator();
            // tsCodeGenerator.WriteLine("export interface " + @interface.Name);
            // tsCodeGenerator.Block(g =>
            // {
            //     foreach (var property in @interface.Members)
            //     {
            //         g.WriteLine(property.Name + ": " + TsTypeGenerator.Generate(property.Type));
            //     }
            // });
            //
            // var fileName = @interface.Name + ".ts";
            // tsCodeGenerator.WriteToFile(fileName);
        }
    }
}