using System.Reflection;
using Itecho.TsGen.TSExpressions;
using Itecho.TsGen.TsTypes;

namespace Itecho.TsGen;

// dotnet pack
// dotnet tool install --global --add-source ./nupkg inspector  

public static class Program
{
    static void Main(string[] args)
    {
        var versionString = Assembly.GetEntryAssembly()?
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?
            .InformationalVersion;

        if (args.Length == 0)
        {
            Console.WriteLine($"typescript generator v{versionString}");
            Console.WriteLine("-------------");
            Console.WriteLine("\nUsage:");
            return;
        }

        var assemblyPath = args[0];
        Console.WriteLine("Inspecting assembly: " + assemblyPath);

        // Loading assembly dependencies from a complete output path
        // using a custom AssemblyLoadContext and AssemblyDependencyResolver
        var loadContext = new DependencyLoadContext(assemblyPath);
        var assembly = loadContext.LoadFromAssemblyPath(assemblyPath);


        var controllers = ControllerInspector.Inspect(assembly);

        var interfaces = TsConverter.Cache.Values
            .OfType<TsInterface>()
            .ToList();

        // generate interfaces per file
        foreach (var @interface in interfaces)
        {
            var tsFile = new TsFile();
            tsFile.AddBody(TsExp.MultilineComment(
                $"This file was generated by Itecho TS gen v{versionString}",
                "Any changes to this file will be lost if regenerated"));

            tsFile.AddBody(TsExp.DefaultExport(TsExp.Interface(@interface)));

            tsFile.WriteToFile(Path.Combine("/Users/willem/projects/itest-leaf/Web/ClientApp/src/controllers",
                @interface.Name));
        }
    }
}