using Itecho.TsGen.TsTypes;

namespace Itecho.TsGen;

public static class TsGenArguments
{
    public static List<string> Ignore { get; set; } = new();
    public static bool ExplicitReturns { get; set; }

    public static string ControllerFolder { get; set; } = "controllers";
    public static string InterfacesFolder { get; set; } = "interfaces";

    public static string DefaultPattern { get; set; } = "/api/{controller}/{action}";
    
    // methods returning void are generated by defaeult
    public static bool GenerateVoidReturn { get; set; } = true;

    /// <summary>
    /// Generate factories for interfaces being generated
    /// </summary>
    public static bool GenerateFactories { get; set; }
    
    public static TsEnum.TsEnumValueType EnumValueType { get; set; } = TsEnum.TsEnumValueType.String;

    public static void Fill(List<ProcessArguments.Args> list)
    {
        foreach (var arg in list)
        {
            switch (arg.Name)
            {
                case "factories":
                    GenerateFactories = true;
                    break;
                case "defaultPattern":
                    DefaultPattern = arg.Value.FirstOrDefault() ?? "/{controller}/{action}";
                    break;
                case "disableVoidReturns":
                    GenerateVoidReturn = false;
                    break;
                case "ignore":
                    Ignore = arg.Value.Select(f => f.ToLower()).ToList();
                    break;
                case "explicitReturns":
                    ExplicitReturns = true;
                    break;
                case "enum":
                    EnumValueType = arg.Value.Contains("string") ? TsEnum.TsEnumValueType.String : TsEnum.TsEnumValueType.Number;
                    break;
            }
        }

    }
}