using System.Reflection;
using Itecho.TsGen.TSExpressions;

namespace Itecho.TsGen;

public static class VersionInfo
{
    public static readonly string VersionString = Assembly.GetEntryAssembly()?
        .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?
        .InformationalVersion ?? "";

    public static readonly TsExp GenerationNotice = TsExp.MultilineComment(
        $"This file was generated by Itecho.TSGen tool",
        "Version and info generated in .version",
        "Any changes to this file will be lost if regenerated ");
}